# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsBeneficiarie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(blank=True, decimal_places=4, max_digits=6, verbose_name='доля бенефициара в активе, %')),
                ('rel_date', models.DateField(auto_now_add=True, verbose_name='дата актуальности')),
                ('source', models.CharField(max_length=40, verbose_name='источник')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiariesOffshore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_date', models.DateField(auto_now_add=True, verbose_name='дата актуальности')),
                ('source', models.CharField(max_length=40, verbose_name='источник')),
            ],
        ),
        migrations.CreateModel(
            name='OffshoresAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(blank=True, decimal_places=4, max_digits=6, verbose_name='доля бенефициара в активе, %')),
                ('rel_date', models.DateField(auto_now_add=True, verbose_name='дата актуальности')),
                ('source', models.CharField(max_length=40, verbose_name='источник')),
            ],
        ),
        migrations.RenameModel(
            old_name='Assets',
            new_name='Asset',
        ),
        migrations.RenameModel(
            old_name='Beneficiaries',
            new_name='Beneficiarie',
        ),
        migrations.RenameModel(
            old_name='Offshores',
            new_name='Offshore',
        ),
        migrations.RemoveField(
            model_name='assetsbeneficiaris',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetsbeneficiaris',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='beneficiaryoffshore',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='beneficiaryoffshore',
            name='offshore',
        ),
        migrations.RemoveField(
            model_name='offshoreasset',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='offshoreasset',
            name='offshore',
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'актив'},
        ),
        migrations.AlterModelOptions(
            name='beneficiarie',
            options={'ordering': ['ben_lastname', 'ben_name'], 'verbose_name': 'бенефициар'},
        ),
        migrations.DeleteModel(
            name='AssetsBeneficiaris',
        ),
        migrations.DeleteModel(
            name='BeneficiaryOffshore',
        ),
        migrations.DeleteModel(
            name='OffshoreAsset',
        ),
        migrations.AddField(
            model_name='offshoresasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Asset', verbose_name='актив'),
        ),
        migrations.AddField(
            model_name='offshoresasset',
            name='offshore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Offshore', verbose_name='офшор'),
        ),
        migrations.AddField(
            model_name='beneficiariesoffshore',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Beneficiarie', verbose_name='бенефициар'),
        ),
        migrations.AddField(
            model_name='beneficiariesoffshore',
            name='offshore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Offshore', verbose_name='офшор'),
        ),
        migrations.AddField(
            model_name='assetsbeneficiarie',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Asset', verbose_name='актив'),
        ),
        migrations.AddField(
            model_name='assetsbeneficiarie',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Beneficiarie', verbose_name='бенефициар'),
        ),
    ]
