# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20160721_2209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetsBeneficiarie',
            new_name='AssetsBeneficiaries',
        ),
        migrations.RenameModel(
            old_name='Beneficiarie',
            new_name='Beneficiary',
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'актив', 'verbose_name_plural': 'активы'},
        ),
        migrations.AlterModelOptions(
            name='assetsbeneficiaries',
            options={'verbose_name': 'Связь Активы-бенефициры', 'verbose_name_plural': 'Связи Активы-бенефициры'},
        ),
        migrations.AlterModelOptions(
            name='beneficiariesoffshore',
            options={'verbose_name': 'Связь Бенефициары-Офшоры', 'verbose_name_plural': 'Связи Бенефициары-Офшоры'},
        ),
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'ordering': ['ben_lastname', 'ben_name'], 'verbose_name': 'бенефициар', 'verbose_name_plural': 'бенефициары'},
        ),
        migrations.AlterModelOptions(
            name='offshore',
            options={'verbose_name': 'офшор', 'verbose_name_plural': 'офшоры'},
        ),
        migrations.AlterModelOptions(
            name='offshoresasset',
            options={'verbose_name': 'Связь Офшоры-Активы', 'verbose_name_plural': 'Связи Офшоры-Активы'},
        ),
    ]
