# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20160721_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeneficiariesOffshore',
            new_name='BeneficiariesOffshores',
        ),
        migrations.RenameModel(
            old_name='OffshoresAsset',
            new_name='OffshoresAssets',
        ),
    ]
