# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20160721_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsbeneficiaries',
            name='source',
            field=models.CharField(blank=True, max_length=40, verbose_name='источник'),
        ),
        migrations.AlterField(
            model_name='offshoresassets',
            name='share',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, verbose_name='доля офшора в активе, %'),
        ),
    ]
