# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20160721_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsbeneficiaries',
            name='rel_date',
            field=models.DateField(blank=True, verbose_name='дата актуальности'),
        ),
    ]
